name: build_the_webclient
on:
  push:
    branches: ["webclient"]
defaults:
  run:
    working-directory: webclient
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run generate_api
      - run: npm run build

