name: build_the_webclient
on:
  push:
    branches: ["webclient"]
defaults:
  run:
    working-directory: webclient
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # alias v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # alias v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm run generate_api
      - run: npm run build

