name: 'Editor Config format check'

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  validate:
    name: Validate Editor Config formatting
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout PR head branch
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      with:
        fetch-depth: 0
    - name: Editor Config Validation against PR base commit
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_EDITORCONFIG: true
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.sha }}
